In [1]:
import numpy as np
import pandas as pd

In [2]:
# Level 3: Indexing & Slicing

# 11 Extract the 2nd row from a 2D array.

# 12 Extract the last column from a matrix.

# 13 From a 1D array, select all values greater than 25.

# 14 Modify a slice of an array without using a loop.

# 15 Reverse a NumPy array.

In [6]:
# 11 Extract the 2nd row from a 2D array.

arr1 = np.arange(20).reshape(5,4)
print(arr1)


print(arr1[1])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[4 5 6 7]


In [9]:
# 12 Extract the last column from a matrix 
last_column = arr1[:,-1]
print(last_column)


[ 3  7 11 15 19]


In [15]:
# 13 From a 1D array, select all values greater than 25.

arr_1D = np.random.randint(15,50,20)
print(arr_1D)
print(arr_1D.size)

result = arr_1D[arr_1D > 25]

print("All values greater than 25 are : ",result)



[45 32 37 47 28 41 38 15 30 16 24 25 47 46 46 15 18 24 44 49]
20
All values greater than 25 are :  [45 32 37 47 28 41 38 30 47 46 46 44 49]


In [17]:
# 14 Modify a slice of an array without using a loop.

arr = np.array(np.arange(20))
print(arr)
print(arr.size)

arr[4:8] = 10
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
20
[ 0  1  2  3 10 10 10 10  8  9 10 11 12 13 14 15 16 17 18 19]


In [22]:
# 15 Reverse a NumPy array.

print(arr)

result = arr[::-1]
print(result)

[ 0  1  2  3 10 10 10 10  8  9 10 11 12 13 14 15 16 17 18 19]
[19 18 17 16 15 14 13 12 11 10  9  8 10 10 10 10  3  2  1  0]
