In [6]:
import numpy as np
import pandas as pd

In [7]:
# Level 4: Logical & Advanced

# 16 Find indices where values are greater than the mean.

# 17 Check if two arrays are equal element-wise.

# 18  Sort an array.

# 19 Compute the dot product of two arrays.

# 20 Stack two arrays:

# Vertically

# Horizontally

In [8]:
# 16 Find indices where values are greater than the mean .. 
values = np.random.randint(20,60,10)
print(values)

mean_value = np.mean(values)
print(mean_value)

indices = values > mean_value
print(indices)

[22 32 21 38 45 21 44 50 44 59]
37.6
[False False False  True  True False  True  True  True  True]


In [ ]:
# 17 Check if two arrays are equal element-wise.
arr_1 = np.array([10,20,30,40,50])
arr_2 = np.array([1,2,3,4,5])


result = np.array_equal(arr_1,arr_2)

print(result)

False


In [11]:
# 18 Sort an array.
numpy_array = np.array([70,80,90,10,20,30,40,50])
result = np.sort(numpy_array)
print(result)

[10 20 30 40 50 70 80 90]


In [12]:
# 19 Compute the dot product of two arrays.
arr_1 = np.array([10,20,30,40,50])
arr_2 = np.array([1,2,3,4,5])

result = np.dot(arr_1,arr_2)
print(result)

550


In [19]:
# 20 Stack two arrays:
# Vertically
arr_1 = np.array([10,20,30,40,50])
arr_2 = np.array([1,2,3,4,5])

result1 = np.vstack((arr_1,arr_2))
print(result1)

# Horizontally
result2 = np.hstack((arr_1,arr_2))
print(result2)


[[10 20 30 40 50]
 [ 1  2  3  4  5]]
[10 20 30 40 50  1  2  3  4  5]
