In [1]:
import numpy as np
import pandas as pd 

In [2]:
# Level 2: Array Operations

# 6 Create two arrays of size 5 and perform:

# Addition

# Subtraction

# Multiplication

# 7  Multiply every element of an array by 3.

# 8 Find the maximum, minimum, mean, and standard deviation of an array.

# 9 Replace all odd numbers in an array with -1.

# 10 Reshape a 1D array of size 12 into a 3×4 matrix.

In [5]:
# 6 Create two arrays of size 5 and perform 
# addition
# subtraction
# multiplication 

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print(arr1+ arr2)
print(arr1-arr2)
print(arr1 * arr2)

[11 22 33 44 55]
[ -9 -18 -27 -36 -45]
[ 10  40  90 160 250]


In [7]:
# 7 Multiply every element of an array by 3.
print(arr1)
result = arr1 * 3 
print(result)

[1 2 3 4 5]
[ 3  6  9 12 15]


In [15]:
# 8 Find the maximum, minimum, mean, and standard deviation of an array.
arr3 = np.array(np.arange(20).reshape(5,4))
print(type(arr3))
print(np.mean(arr3))
print(np.std(arr3))
print(np.max(arr3))

<class 'numpy.ndarray'>
9.5
5.766281297335398
19


In [20]:
# 9 Replace all odd numbers in an array with -1.

odd_indices = arr3 % 2 != 0
print(odd_indices)

arr3[odd_indices] = -1
print(arr3)


[[False  True False  True]
 [False  True False  True]
 [False  True False  True]
 [False  True False  True]
 [False  True False  True]]
[[ 0 -1  2 -1]
 [ 4 -1  6 -1]
 [ 8 -1 10 -1]
 [12 -1 14 -1]
 [16 -1 18 -1]]


In [26]:
# 10 Reshape a 1D array of size 12 into a 3×4 matrix.

arr4 = np.arange(12)
print(arr4)
print(arr4.ndim)
print(arr4.size)

new_arr4 = arr4.reshape(3,4)
print(new_arr4)
print(new_arr4.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1
12
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
12
