In [1]:
import numpy as np
import pandas as pd

In [ ]:
# Level 1: Basics (Warm-up)

# 1 Create a NumPy array of integers from 10 to 50.

# 2 Create a 5×5 matrix filled with zeros.

# 3 Create a 3×3 identity matrix.

# 4 Generate an array of 20 random numbers between 0 and 1.

# 5 Find the shape, size, and datatype of a given array

In [4]:
# 1 Create a Numpy array of integers from 10 to 50 

numpy_array1 = np.array(np.arange(10,51))
print(numpy_array1)
print(type(numpy_array1))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
<class 'numpy.ndarray'>


In [5]:
# 2 Create a 5×5 matrix filled with zeros.
numpy_array2 = np.zeros((5,5))
print(numpy_array2)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [11]:
# 3 Create a 3×3 identity matrix.
numpy_array3 = np.identity(3)
# numpy_array3 = np.identity((3,3)) # {This gives error because , .idenitiy() expects only one number as ,it always creates square matrix so why to give two values one value is enough , so it is designed in such a way where it only accepts one integer.. }

print(numpy_array3)
print(numpy_array3.shape)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
(3, 3)


In [17]:
# 4 Generate an array of 20 random numbers between 0 and 1.

numpy_array4 = np.random.rand(20)
print(numpy_array4)
print(numpy_array4.size)
print(numpy_array4.shape)

[0.36998163 0.40305888 0.91746811 0.26542762 0.2564629  0.22236957
 0.11327881 0.8634833  0.52468638 0.90416483 0.96617874 0.47875216
 0.77630204 0.80327457 0.15302554 0.96279536 0.76199215 0.20206712
 0.38159028 0.52596663]
20
(20,)


In [23]:
# 5 Find the shape, size, and datatype of a given array.
numpy_array5 = np.random.randint(0,20,20).reshape(5,4)
print(numpy_array5)
print(numpy_array5.size)
print(numpy_array5.shape)
print(numpy_array5.dtype)

[[15 11  5 11]
 [ 5  9 15 18]
 [17  8  9  0]
 [15 13 19 19]
 [ 6  5 14  8]]
20
(5, 4)
int32
